export const desktopCardList = [
  {
    gridRow: "1 / 6",
    gridColumn: "1 / 5",
    backgroundColor: "yellow",
    isSmall: false,
    name: "Schedule-e-Hamdard",
    info: "A class scheduler consisting of three modules mainly staff, teachers, and students. Where faculty member can assign classes to teachers, teachers can schedule sessions for assigned classes and students can keep track of upcoming sessions.",
    viewLink: "https://github.com/yahya-cloud/schedule-e-hamdard",
    gitLink: "https://github.com/yahya-cloud/schedule-e-hamdard",
    imgUrl: "/images/project-1.png",
  },
  {
    gridRow: "6 / 11",
    gridColumn: "1 / 5",
    backgroundColor: "yellow",
    isSmall: false,
    name: "Mollify Web-App",
    info: "A web-app where patients can find psychiatrist and request session both doctor and patient can navigate each other from there present location. It have different UI for patients and doctors. Technology stack used:- React.js, Node.js, Express, Redux, MongoDb, JWT, Material UI, Geolocation api, MapboxGL, Chart.js,  Designed using Figma, deployed on Heroku.",
    viewLink: "https://mollify-webapp.herokuapp.com/",
    gitLink: "https://github.com/yahya-cloud/mollify-webapp",
    imgUrl: "/images/MollifyWebApp.jpeg",
  },
  {
    gridRow: "1 / 4",
    gridColumn: "5 / 9",
    backgroundColor: "pink",
    isSmall: false,
    name: "Mollify website",
    info: "A multipage website for introducing the idea of mollify and letting interested people contact us via email. Technology Stack:- Node.js, EJS, Express, SCSS, Chart.js,Email.js, Designed using Figma.",
    viewLink: "https://frozen-sands-98963.herokuapp.com/",
    gitLink: "https://github.com/yahya-cloud/mollify-node",
    imgUrl: "/images/MollifyWebPage.png",
  },

  {
    gridRow: "4 / 7",
    gridColumn: "5 / 7",
    backgroundColor: "orange",
    isSmall: false,
    name: "Buger App",
    info: "Web-app to make desired burger, place order, see order history. Technology Stack:- React.js, Redux, ReduxSaga, Firebase ",
    viewLink: "https://burger-builder-d34c6.firebaseapp.com",
    gitLink: "https://github.com/yahya-cloud/burger-app",
    imgUrl: "/images/burgerApp.png",
  },
  {
    gridRow: "7 / 9",
    gridColumn: " 5 / 7",
    backgroundColor: "rgb(255, 46, 46)",
    isSmall: true,
    name: "BankerList",
    info: "Technology Stack:- JavaScript, HTML, CSS ",
    viewLink: "https://yahya-cloud.github.io/bankerlist/",
    gitLink: "https://github.com/yahya-cloud/bankerlist",
    imgUrl: "/images/bankerList.jpg",
  },
  {
    gridRow: "9 / 11",
    gridColumn: "5 / 7",
    backgroundColor: "lightcoral",
    isSmall: true,
    name: "whatsapp-clone",
    info: "Technology Stack:- React.js, Redux, Firebase",
    viewLink: "https://whatsapp-clone-2aa06.firebaseapp.com/",
    gitLink: "https://github.com/yahya-cloud/whatsapp-clone",
    imgUrl: "/images/whatsapp.png",
  },

  {
    gridRow: "4 / 7",
    gridColumn: " 7 / 9",
    backgroundColor: "lightsalmon",
    isSmall: false,
    info: "Js app to get food recipes and amount of ingredients for different number of people. Technology stack:- JS, Webpack, HTML, CSS   ",
    name: "Forkify",
    viewLink: "https://agitated-brattain-a2b130.netlify.app/",
    gitLink: "https://github.com/yahya-cloud/forkify",
    imgUrl: "/images/forkify.jpg",
  },
  {
    gridRow: "7 / 9",
    gridColumn: "  7 / 9",
    backgroundColor: "lawngreen",
    isSmall: true,
    name: "Mapty",
    info: "Technology Stack:- JavaScript, Leaflet, HTML, CSS",
    viewLink: "https://yahya-cloud.github.io/mapty/",
    gitLink: "https://github.com/yahya-cloud/mapty",
    imgUrl: "/images/mapty.jpg",
  },
  {
    gridRow: "9 / 11",
    gridColumn: " 7 / 9",
    backgroundColor: "lightslategrey",
    isSmall: true,
    name: "Tinder clone",
    info: "Technology Stack:- React.js, Redux, Firebase",
    viewLink: "https://tinder-clone-6ccc5.web.app/",
    gitLink: "https://github.com/yahya-cloud/tinder-clone",
    imgUrl: "/images/tinder.png",
  },

  {
    gridRow: "4 / 6",
    gridColumn: " 9 / 10",
    backgroundColor: "lightyellow",
    isSmall: true,
    name: "Portfolio",
    info: "Tech. Stack:- React.js",
    viewLink: "https://www.mohammadyahya.in/",
    gitLink: "https://github.com/yahya-cloud/portfolio",
    imgUrl: "/images/portfolio.png",
  },
  {
    gridRow: "4 / 6",
    gridColumn: "10 / 11",
    backgroundColor: "lightseagreen",
    isSmall: true,
    name: "Pig game",
    info: "Tech. Stack:- Javascript",
    viewLink: "https://yahya-cloud.github.io/piggame/",
    gitLink: "https://github.com/yahya-cloud/piggame",
    imgUrl: "/images/pigGame.jpg",
  },
  {
    gridRow: "6 / 8",
    gridColumn: "10 / 11",
    backgroundColor: "rgb(193, 182, 255)",
    isSmall: true,
    name: "Notes App",
    info: "Tech. Stack:- React.js",
    viewLink: "https://w7pvg.csb.app/",
    gitLink: "https://codesandbox.io/s/keeper-app-w7pvg?file=/src/index.js",
    imgUrl: "/images/notesApp.png",
  },

  {
    gridRow: "6 / 8",
    gridColumn: " 9 / 10",
    backgroundColor: "rgb(236, 154, 61)",
    isSmall: true,
    name: "Budgety",
    info: "Tech. Stack:- JavaScript",
    viewLink: "https://yahya-cloud.github.io/mydatebudget/",
    gitLink: "https://github.com/yahya-cloud/mydatebudget",
    imgUrl: "/images/budgety.jpg",
  },
  {
    gridRow: "8 / 9",
    gridColumn: "9 / 10",
    backgroundColor: "rgb(104, 61, 12)",
    isSmall: true,
    name: "Mars App ",
    info: "",
    viewLink: "https://yahya-cloud.github.io/mars-app/",
    gitLink: "https://github.com/yahya-cloud/mars-app",
    imgUrl: "/images/marsapp.jpg",
  },
  {
    gridRow: "10 / 11",
    gridColumn: "10 / 11",
    backgroundColor: "rgb(12, 104, 20) ",
    isSmall: true,
    name: "Js app",
    viewLink: "https://yahya-cloud.github.io/meditaion-app/",
    gitLink: "https://github.com/yahya-cloud/mars-app",
    imgUrl: "/images/meditationApp.jpg",
  },
  {
    gridRow: "9/10",
    gridColumn: "9/10",
    backgroundColor: "rgb(26, 159, 177)",
    isSmall: true,
    name: "Naturous",
    info: "commonly used to demonstrate the visual",
    viewLink: "https://yahya-cloud.github.io/natours/",
    gitLink: "https://github.com/yahya-cloud/natours",
    imgUrl: "/images/naturous.jpg",
  },
  {
    gridRow: "9 / 10",
    gridColumn: "10 / 11",
    backgroundColor: "rgb(177, 129, 26) ",
    isSmall: true,
    name: "Atlas",
    info: "",
    viewLink: "https://yahya-cloud.github.io/atalas-creative/",
    gitLink: "https://github.com/yahya-cloud/atalas-creative",
    imgUrl: "/images/atlas.jpg",
  },
  {
    gridRow: "10 / 11",
    gridColumn: "9/10",
    backgroundColor: "rgb(199, 82, 82)",
    isSmall: true,
    name: "webpage",
    viewLink: "https://yahya-cloud.github.io/tider-e-hamdard/",
    gitLink: "https://yahya-cloud.github.io/tider-e-hamdard/",
    imgUrl: "/images/tinder_e_hamdard.jpg",
  },
  {
    gridRow: "1 / 4",
    gridColumn: "9/11",
    backgroundColor: "lavender",
    isSmall: false,
    name: "Memories",
    info: "A web-app where people can store there memories see others. Technology Stack:- React.js, Node.js, Redux, Express, MongoDb, JWT, Materiel UI. ",
    viewLink: "https://sheltered-bayou-78627.herokuapp.com/",
    gitLink: "https://github.com/yahya-cloud/memories",
    imgUrl: "/images/memories.png",
  },
  {
    gridRow: "8 / 9 ",
    gridColumn: "10 / 11",
    backgroundColor: "black",
    isSmall: true,
    name: "Nexter",
    info: "commonly used to demonstrate the visual",
    viewLink: "https://yahya-cloud.github.io/nexter/",
    gitLink: "https://github.com/yahya-cloud/nexter",
    imgUrl: "/images/nexter.jpg",
  },
];

export const mobileCardList = [
  {
    ...desktopCardList[0],
    gridRow: "1 / 5",
    gridColumn: "1 / 5",
    info: "Technology stack used:- React.js, Node.js, Express, Redux, MongoDb,  MapboxGL",
    isSmall: true,
  },
  {
    ...desktopCardList[2],
    gridRow: "1 / 3",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[3],
    gridRow: "3 / 5",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },

  {
    ...desktopCardList[1],
    info: "Technology stack:- React.js, Express, Node.js, Mongodb, Redux, JWT, React-Bootstrap",
    gridRow: " 5 / 9",
    gridColumn: "1 / 5",
    isSmall: true,
  },
  {
    ...desktopCardList[6],
    gridRow: "5 / 7",
    gridColumn: "5 / 7 ",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[7],
    gridRow: "7 / 9",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[18],
    info: "Technology stack:- React.js, Express, Node.js, Mongodb, Redux, JWT",
    gridRow: "9 / 13",
    gridColumn: "1 / 5",
    isSmall: true,
  },
  {
    ...desktopCardList[9],
    gridRow: "9 / 11",
    info: "",
    gridColumn: "5 / 7",
    isSmall: true,
  },
  {
    ...desktopCardList[4],
    gridRow: "11 / 13",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },

  {
    ...desktopCardList[8],
    gridRow: "13 / 15",
    gridColumn: "1 / 3",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[5],
    gridRow: "13 / 15",
    gridColumn: "3 / 5",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[11],
    gridRow: "13 / 15",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },

  {
    ...desktopCardList[15],
    gridRow: "15/ 17",
    gridColumn: "1 / 3",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[12],
    gridRow: "15/ 17",
    gridColumn: "3 / 5",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[14],
    gridRow: "15/ 17",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[13],
    gridRow: "17 / 19",
    gridColumn: "1 / 3",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[16],
    gridRow: "17 / 19",
    gridColumn: "3 / 5",
    info: "",
    isSmall: true,
  },
  {
    ...desktopCardList[17],
    gridRow: "17 / 19",
    gridColumn: "5 / 7",
    info: "",
    isSmall: true,
  },
];
