export const ExperienceList = [
  {
    name: "SIEMENS",
    bulletPoints: [
      "Contributed to the frontend development of a factory orders quality assurance application being piloted across 10 Siemens factories globally, including two in Germany.",
      "Refactored a legacy frontend codebase into a domain-driven architecture, improving maintainability through structured state management, and utilized an internal MCP server to upgrade libraries and outdated code.",
      "Developed the frontend and contributed to the backend of a document management system for factory machines, with dashboards for machine and department hierarchies, improving access to operating and safety documents.",
      "Implemented multiprocessing in a FastAPI server wrapping a Factory Inventory Simulation Model, enabling parallel simulation runs across multiple CPU cores and achieving a 4x speedup in execution time.",
      "Optimized handling of large datasets generated by a simulation model through Parquet file storage and chunked uploads/reads, and built visualizations that helped data scientists interpret and improve the model.",
      "Designed database schemas, implemented migrations while preserving legacy data, strengthened reliability across applications through comprehensive testing, and reduced CI build times through Docker layer caching."
    ],
    timeline: { start: "JULY 2024", end: "Present" },
    location: { country: "Germany", city: "Berlin" },
    position: "Software Engineer - Working Student",
    website: "https://www.siemens.com/de-de/",
    industry: "Industrial Manufacturing"
  },
  {
    name: "Solana Labs",
    bulletPoints: [
      "Selected as one of the 90 developers globally to attend the MLH fellowship program.",
      "During the fellowship period, I worked with Solana Labs and contributed to the main Solana blockchain explorer web application.",
      "Enhanced user experience of the web application by presenting information about inactive accounts, improved UI, resolved open-source bugs reported by the community and displayed complex nested data structures of Solana blockchain programs on the frontend."
    ],
    timeline: { start: "SEP 2022", end: "DEC 2022" },
    location: { country: "USA", city: "Remote" },
    position: "Software Engineer - Intern",
    website: "https://www.solanalabs.com/",
    industry: "Blockchain"
  },
  {
    name: "Major League Hacking",
    bulletPoints: [
      "Worked with a pod of 15 people worldwide by collaborating on two projects, gave regular standups and retrospectives.",
      "Built a Jenkins portfolio website and a performant weather app using React."
    ],
    timeline: { start: "APR 2022", end: "MAY 2022" },
    location: { country: "USA", city: "Remote" },
    position: "Software Engineer - Intern",
    website: "https://www.mlh.com/",
    industry: "Global community for developer's education"    
  }
];
